#!/bin/bash -e

#define some color
GREEN="\\033[0;32m"
RED="\\033[1;31m"
WHITE="\\033[0;02m"
YELLOW="\\033[1;33m"
CYAN="\\033[1;36m"
NORMAL="\033[0m"
SHORT=$0

function print_green {
    echo -e "${GREEN}$1 $NORMAL"
}

function print_yellow {
    echo -e "${YELLOW}$1 $NORMAL"
}

function print_red {
    echo -e "${RED}$1 $NORMAL"
}

USER=cashin

ENVIRONMENT=${ENVIRONMENT:=dev}

if [ -z "$action" ];then action=$1; fi

#Starts or restarts containers and basic init tasks
function _init {
    print_green "Re/Starting containers for '${ENVIRONMENT}' machine"

    docker-compose up -d --build

    cp -n .env.example .env

    _update ${@:2}

    docker exec $(docker-compose ps -q app) bash -c 'php artisan key:generate'
    docker exec $(docker-compose ps -q app) bash -c 'php artisan migrate'
}

function _update {
    docker exec --user 1000 $(docker-compose ps -q app) bash -c "composer install"

    docker exec $(docker-compose ps -q app) bash -c "chown -R $USER:www-data storage"
    docker exec $(docker-compose ps -q app) bash -c "chmod -R 775 ./storage/"
}

function _deploy {
   TAG=$1
   $(aws ecr get-login --no-include-email --region ap-southeast-2)

   docker build -f dockerfiles/php-nginx/Dockerfile -t app .
   docker tag app:latest 893628615201.dkr.ecr.us-east-2.amazonaws.com/app:$TAG
   docker push 310639701108.dkr.ecr.ap-southeast-2.amazonaws.com/php-nginx:$TAG
   docker push 310639701108.dkr.ecr.ap-southeast-2.amazonaws.com/php-nginx:latest

   ecs-deploy -c production -n api-service -i 310639701108.dkr.ecr.ap-southeast-2.amazonaws.com/php-nginx:$TAG
   aws ecs run-task --cluster production --task-definition migrate-db
}


### Command Handler
case "$1" in
init)
    _init $2
;;
update)
    _update $2
;;
deploy)
    _deploy $2
;;
shell)
    docker exec -it --user 1000 $(docker-compose ps -q app) bash
;;
*)
echo -e "$CYAN "
echo -e "$CYAN 
############# Tools ############# "
echo -e "$CYAN"
echo -e "$NORMAL$SHORT $YELLOW init $GREEN 'Setup/update app."
echo -e "$NORMAL$SHORT $YELLOW update $GREEN 'Update app."
echo -e "$NORMAL$SHORT $YELLOW shell $GREEN 'Opens shell of app container as host machine user'"
echo -e "$NORMAL"
esac
